name: Production

on:
  push:
    tags:
      - v*

jobs:
  register-frontend:
      name: Register front-end
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Create image labels and tags
          id: docker_meta
          uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
          with:
            images: horekk/devops-test
            labels: |
              org.opencontainers.image.title=frontend-devops
              org.opencontainers.image.documentation=https://github.com/HoreKk/devops-test
            tags: |
              type=sha
              type=ref,event=pr
              type=ref,event=branch
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
        - name: Set up Buildx
          id: buildx
          uses: docker/setup-buildx-action@master
          with:
            install: true

        - name: Registry authentication
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set buildx cache up
          uses: actions/cache@v2
          with:
            key: "${{ runner.os }}-buildx-frontend-devops"
            path: /tmp/.buildx-frontend-devops-cache
            restore-keys: |
              ${{ runner.os }}-buildx-frontend-devops

        - name: Image build and register
          uses: docker/build-push-action@v2
          with:
            context: ./frontend
            push: "true"
            builder: ${{ steps.buildx.outputs.name }}
            tags: "${{ steps.docker_meta.outputs.tags }}"
            labels: "${{ steps.docker_meta.outputs.labels }}"
            cache-to: "type=local,dest=/tmp/.buildx-frontend-devops-cache"
            cache-from: "type=local,src=/tmp/.buildx-frontend-devops-cache"