name: Production

on:
  create:
    tags:
      - v*

jobs:
  register-frontend:
      name: Register front-end
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Create image labels and tags
          id: docker_meta
          uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
          with:
            images: ghcr.io/HoreKk/devops-test/devops-frontend
            labels: |
              org.opencontainers.image.title=frontend-devops
              org.opencontainers.image.documentation=https://github.com/HoreKk/devops-test
            tags: |
              type=sha
              type=ref,event=pr
              type=ref,event=branch
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

        - name: Registry authentication
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}

        - name: Image build and register
          uses: docker/build-push-action@v2
          with:
            context: ./frontend
            push: "true"
            tags: "${{ steps.docker_meta.outputs.tags }}"
            labels: "${{ steps.docker_meta.outputs.labels }}"